apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-contacts
  namespace: tc3
  labels:
    app: delete-contacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-contacts
  template:
    metadata:
      labels:
        app: delete-contacts
    spec:
      containers:
      - name: delete-contacts
        image: fiaptech3acr.azurecr.io/tc3-delete-contact:latest #usar tag e nome do container como variáveis no build para simplificar a reutilização.
        ports:
        - containerPort: 8083
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8083"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: delete-contacts-service
  namespace: tc3
spec:
  selector:
    app: delete-contacts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: ClusterIP