apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-contact-worker
  namespace: PLACEHOLDER_NAMESPACE
  labels:
    app: delete-contact-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-contact-worker
  template:
    metadata:
      labels:
        app: delete-contact-worker
    spec:
      containers:
      - name: delete-contact-worker
        image: PLACEHOLDER_CONTAINER_REGISTRY/PLACEHOLDER_IMAGE_REPOSITORY:PLACEHOLDER_TAG #usar tag e nome do container como variáveis no build para simplificar a reutilização.
        ports:
        - containerPort: 8093
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: delete-contact-worker-service
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    app: delete-contact-worker
  ports:
    - protocol: TCP
      port: 8093
      targetPort: 8093
  type: ClusterIP